!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 29 Jul 2025 17:17
!
MODULE MAIN_MODULE_DIFF
  USE BUFLOWMODULE_DIFF
  USE MESHDEFORMATIONN_DIFF
  IMPLICIT NONE

CONTAINS
!  Differentiation of main in forward (tangent) mode (with options i4 dr8 r4 i4 dr8 r4 i4 dr8 r4 i4 dr8 r4 i4 dr8 r4):
!   variations   of useful results: [alloc*sol in initializeuniformsolution3d]
!   with respect to varying inputs: input_param
!   RW status of diff variables: [alloc*sol in initializeuniformsolution3d]:out
!                cellprimitivesout:(loc) input_param:in
!   Plus diff mem management of: [alloc*sln in solve].cellstate:in-out
!                [alloc*sln in solve].cellfluxes:in-out [alloc*sln in solve].cellprimitives:in-out
!                [alloc*sln in solve].fluxresiduals:in-out [alloc*sln in solve].facefluxes:in-out
! 模块内包含子程序，自动生成显式接口
  SUBROUTINE MAIN_D(input_param, input_paramd, cellprimitivesout, &
&   cellprimitivesoutd)
    IMPLICIT NONE
!$AD &input_param          ! 标记输入
!$AD &cellPrimitives       ! 标记输出
! 输入参数：仅原data_4D137的第一个维度（标量）
    REAL(kind=8), INTENT(IN) :: input_param
    REAL(kind=8), INTENT(IN) :: input_paramd
    REAL(kind=8), ALLOCATABLE :: cellprimitives(:, :)
! 输出参数：CFD结果（二维可分配数组）
    REAL(kind=8), ALLOCATABLE, INTENT(OUT) :: cellprimitivesout(:, :)
    REAL(kind=8), ALLOCATABLE, INTENT(OUT) :: cellprimitivesoutd(:, :)
! 局部变量：构造1×4变形参数
    REAL(kind=8) :: data_4d137(1, 4)
    REAL(kind=8) :: data_4d137d(1, 4)
! 传递变形网格点的变量
    INTEGER :: ncells, meshinfo(4)
    REAL(kind=8), ALLOCATABLE :: point_update(:, :)
    REAL(kind=8), ALLOCATABLE :: point_updated(:, :)
    CHARACTER(len=256) :: meshpath
    TYPE(MESHH) :: mesh
    INTRINSIC ALLOCATED
!       !$AD intent(out) :: cellPrimitives(nCells, 5)  ! 强制 Tapenade 识别维度（nCells 已定义）[-0.75d0, 0.485d0, -0.
!588d0, -0.912d0]
! 构造变形参数（仅第一个维度为输入，其余为0）
    data_4d137d = 0.0_8
    data_4d137d(1, 1) = input_paramd
    data_4d137(1, 1) = input_param
    data_4d137d(1, 2) = 0.0_8
    data_4d137(1, 2) = 0.485d0
    data_4d137d(1, 3) = 0.0_8
    data_4d137(1, 3) = -0.588d0
! 后三个维度固定为0
    data_4d137d(1, 4) = 0.0_8
    data_4d137(1, 4) = -0.912d0
! 读取网格
!		meshPath = "mesh/OFairfoilMesh"	
!		mesh = OpenFOAMMesh(meshPath, point_update)
! 修改后的代码
!		meshInfo = unstructuredMeshInfo(mesh) 
!		nCells = meshInfo(1)  
!		allocate(cellPrimitives(nCells, 5)) 
    ALLOCATE(cellprimitives(18513, 5), source=0.0d0)
    ALLOCATE(cellprimitivesout(18513, 5), source=0.0d0)
! 显式赋值，确保 Tapenade 识别为“活跃输出”
    cellprimitives = 0.0d0
! 调用网格变形，获取变形后的网格点（point_update）
    CALL AIRFOIL_DEFORMATION_HH_D(data_4d137, data_4d137d, point_update&
&                           , point_updated)
! 调用CFD计算，传入变形网格点，输出结果到cellPrimitives
    CALL COMPUTE_CFD_D(point_update, point_updated, cellprimitivesout, &
&                cellprimitivesoutd)
! 释放point_update内存
    IF (ALLOCATED(point_update)) THEN
      IF (ALLOCATED(point_updated)) THEN
        DEALLOCATE(point_updated)
      END IF
      DEALLOCATE(point_update)
    END IF
  END SUBROUTINE MAIN_D

! 模块内包含子程序，自动生成显式接口
  SUBROUTINE MAIN(input_param, cellprimitivesout)
    IMPLICIT NONE
!$AD &input_param          ! 标记输入
!$AD &cellPrimitives       ! 标记输出
! 输入参数：仅原data_4D137的第一个维度（标量）
    REAL(kind=8), INTENT(IN) :: input_param
    REAL(kind=8), ALLOCATABLE :: cellprimitives(:, :)
! 输出参数：CFD结果（二维可分配数组）
    REAL(kind=8), ALLOCATABLE, INTENT(OUT) :: cellprimitivesout(:, :)
! 局部变量：构造1×4变形参数
    REAL(kind=8) :: data_4d137(1, 4)
! 传递变形网格点的变量
    INTEGER :: ncells, meshinfo(4)
    REAL(kind=8), ALLOCATABLE :: point_update(:, :)
    CHARACTER(len=256) :: meshpath
    TYPE(MESHH) :: mesh
    INTRINSIC ALLOCATED
!       !$AD intent(out) :: cellPrimitives(nCells, 5)  ! 强制 Tapenade 识别维度（nCells 已定义）[-0.75d0, 0.485d0, -0.
!588d0, -0.912d0]
! 构造变形参数（仅第一个维度为输入，其余为0）
    data_4d137(1, 1) = input_param
    data_4d137(1, 2) = 0.485d0
    data_4d137(1, 3) = -0.588d0
! 后三个维度固定为0
    data_4d137(1, 4) = -0.912d0
! 读取网格
!		meshPath = "mesh/OFairfoilMesh"	
!		mesh = OpenFOAMMesh(meshPath, point_update)
! 修改后的代码
!		meshInfo = unstructuredMeshInfo(mesh) 
!		nCells = meshInfo(1)  
!		allocate(cellPrimitives(nCells, 5)) 
    ALLOCATE(cellprimitives(18513, 5))
    ALLOCATE(cellprimitivesout(18513, 5))
! 显式赋值，确保 Tapenade 识别为“活跃输出”
    cellprimitives = 0.0d0
! 调用网格变形，获取变形后的网格点（point_update）
    CALL AIRFOIL_DEFORMATION_HH(data_4d137, point_update)
! 调用CFD计算，传入变形网格点，输出结果到cellPrimitives
    CALL COMPUTE_CFD(point_update, cellprimitivesout)
! 释放point_update内存
    IF (ALLOCATED(point_update)) THEN
      DEALLOCATE(point_update)
    END IF
  END SUBROUTINE MAIN

END MODULE MAIN_MODULE_DIFF

